export enum ErrorCode {
    // Auth Errors
    AUTH_HEADER_MISSING = 'AUTH_HEADER_MISSING',
    AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
    AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
    AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
    AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
    
    // Validation Errors
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
    
    // Kite/Broker Errors
    KITE_SESSION_EXPIRED = 'KITE_SESSION_EXPIRED',
    KITE_TOKEN_MISSING = 'KITE_TOKEN_MISSING',
    KITE_API_ERROR = 'KITE_API_ERROR',

    // System Errors
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    DB_ERROR = 'DB_ERROR'
}

export enum UserMode {
    REAL = 'REAL',
    MOCK = 'MOCK'
}
